# -*- coding: utf-8 -*-
"""EP2DaniloCho.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z9an8HrABvTRo53jrcy2dRDSNujKzH3d
"""

"""
EP2 - Solução de Sistemas Lineares (b, c, d, e) - Código completo (revisado)
Nome : Danilo Cho (NUSP 10769448)

"""

import numpy as np

# (a) Montagem do sistema (manuscrito) em anexo no pdf

A = np.array([[ 0.0,  5.3, -1.9],
              [11.9,  0.0,  1.9],
              [ 1.0, -1.0, -1.0]], dtype=float)
b = np.array([3.1, 15.2, 0.0], dtype=float)

def print_aug(A, b, title=None):
    """Imprime a matriz aumentada [A|b]."""
    if title: print(title)
    M = np.hstack([A, b.reshape(-1,1)])
    with np.printoptions(precision=6, suppress=True):
        print(M)
    print()

def imprimir_tabela(label, cols, linhas):
    print(f"\n=== {label} ===")
    # Cabeçalho
    header = "| " + " | ".join([f"{c:^14}" for c in cols]) + " |"
    sep    = "|-" + "-|-".join(["-"*14 for _ in cols]) + "-|"
    print(header); print(sep)
    # Linhas
    for row in linhas:
        fmt = []
        for val in row:
            if isinstance(val, (int, np.integer)):
                fmt.append(f"{val:14d}")
            else:
                fmt.append(f"{val:14.10f}")
        print("| " + " | ".join(fmt) + " |")

# (b) Eliminação de Gauss com Pivotamento Parcial (geral n x n)

def gauss_pp(A_in, b_in, verbose=True):
    """
    Eliminação de Gauss com pivotamento parcial.
    Retorna (x, logs), onde 'logs' contém rótulos + estados de [A|b].
    """
    A = A_in.astype(float).copy()
    b = b_in.astype(float).copy()
    n = len(b)
    logs = []

    for k in range(n-1):
        # Pivotamento parcial
        p = k + np.argmax(np.abs(A[k:, k]))
        if np.isclose(A[p, k], 0.0):
            raise ValueError("Matriz singular ou pivô nulo.")
        if p != k:
            A[[k, p]] = A[[p, k]]
            b[[k, p]] = b[[p, k]]
            if verbose:
                logs.append(("Permuta de linhas", A.copy(), b.copy()))

        # Antes da eliminação
        if verbose:
            logs.append((f"Antes eliminação col {k}", A.copy(), b.copy()))

        # Eliminação
        for i in range(k+1, n):
            m = A[i, k] / A[k, k]
            A[i, k:] -= m * A[k, k:]
            b[i] -= m * b[k]

        # Após eliminação
        if verbose:
            logs.append((f"Após eliminação col {k}", A.copy(), b.copy()))

    # Retrosubstituição
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = (b[i] - A[i, i+1:] @ x[i+1:]) / A[i, i]

    if verbose:
        print("Matrizes intermediárias [A|b] até triangular superior:")
        for tag, Alog, blog in logs:
            print_aug(Alog, blog, tag)

    return x, logs

print("#\033[1m \033[4m EXERCÍCIO (b) — Gauss com Pivotamento Parcial \033[0m")
x_gauss, logs_b = gauss_pp(A, b, verbose=True)
print(f"#\033[1m \033[4m Solução: \033[0m I1={x_gauss[0]:.8f}, I2={x_gauss[1]:.8f}, I3={x_gauss[2]:.8f}")

# Teste (b) com matriz 4x4
A4 = np.array([[ 2.0,  -1.0,   0.0,   0.0],
               [-1.0,   2.0,  -1.0,   0.0],
               [ 0.0,  -1.0,   2.0,  -1.0],
               [ 0.0,   0.0,  -1.0,   2.0]], dtype=float)
b4 = np.array([1.0, 0.0, 0.0, 1.0], dtype=float)

print("\n#\033[1m \033[4m Teste (b) — Gauss 4×4 \033[0m")
x4, logs4 = gauss_pp(A4, b4, verbose=True)
print(f"#\033[1m \033[4m Solução 4×4: \033[0m {x4}\n")

# (c) Jacobi
def _header_iterativo(n, rotulo_var="I"):
    cols = ["Iter"] + [f"{rotulo_var}{k+1}" for k in range(n)] + ["erro"]
    header = "| " + " | ".join([f"{c:^14}" for c in cols]) + " |"
    sep    = "|-" + "-|-".join(["-"*14 for _ in cols]) + "-|"
    return header, sep, cols

def jacobi(A, b, x0=None, eps=1e-3, maxit=10_000, imprimir_tabela=True, rotulo_var="I"):
    A = A.astype(float); b = b.astype(float)
    n = len(b)
    x = np.zeros(n) if x0 is None else np.array(x0, dtype=float).copy()
    D = np.diag(A)
    R = A - np.diagflat(D)

    tabela = []
    if imprimir_tabela:
        print("#\033[1m \033[4m EXERCÍCIO (c) — Jacobi (sistema possivelmente permutado) \033[0m")
        header, sep, _ = _header_iterativo(n, rotulo_var)
        print(header); print(sep)

    for k in range(maxit):
        x_new = (b - R @ x) / D
        err = np.max(np.abs(x_new - x))
        tabela.append((k, *x_new.tolist(), err))
        if imprimir_tabela:
            vals = [f"{v: .10f}" for v in x_new]
            linha = f"{k:4d} | " + " | ".join(vals + [f"{err: .6e}"]) + " |"
            print(linha)
        x = x_new
        if err < eps:
            break
    return x, tabela

# Permuta as duas primeiras linhas do sistema (1)
P = np.array([[0,1,0],[1,0,0],[0,0,1]])
A_perm = P @ A
b_perm = P @ b

x_jacobi, tab_j = jacobi(A_perm, b_perm, eps=1e-3, imprimir_tabela=True, rotulo_var="I")
print(f"\n#\033[1m \033[4mSolução (Jacobi): \033[0m I1={x_jacobi[0]:.8f}, I2={x_jacobi[1]:.8f}, I3={x_jacobi[2]:.8f}")
print(f"#\033[1m \033[4m Iterações (Jacobi): \033[0m {len(tab_j)}\n")

# Teste (c) 4×4 com Jacobi
print("\n#\033[1m \033[4m Teste (c) — Jacobi 4×4 \033[0m")
x_jacobi4, tabela_j4 = jacobi(A4, b4, eps=1e-3, imprimir_tabela=True, rotulo_var="x")
print(f"\nSolução aproximada (Jacobi 4×4): {x_jacobi4}")
print(f"Iterações até convergência: {len(tabela_j4)}\n")


# (e) Gauss–Seidel

def gauss_seidel(A, b, x0=None, eps=1e-3, maxit=10_000, imprimir_tabela=True, rotulo_var="I"):
    A = A.astype(float); b = b.astype(float)
    n = len(b)
    x = np.zeros(n) if x0 is None else np.array(x0, dtype=float).copy()

    tabela = []
    if imprimir_tabela:
        print("# (e) Gauss–Seidel")
        header, sep, _ = _header_iterativo(n, rotulo_var)
        print(header); print(sep)

    for k in range(maxit):
        x_old = x.copy()
        for i in range(n):
            s1 = A[i, :i] @ x[:i]
            s2 = A[i, i+1:] @ x_old[i+1:]
            x[i] = (b[i] - s1 - s2) / A[i, i]
        err = np.max(np.abs(x - x_old))
        tabela.append((k, *x.tolist(), err))
        if imprimir_tabela:
            vals = [f"{v: .10f}" for v in x]
            linha = f"{k:4d} | " + " | ".join(vals + [f"{err: .6e}"]) + " |"
            print(linha)
        if err < eps:
            break
    return x, tabela

x_gs, tab_gs = gauss_seidel(A_perm, b_perm, eps=1e-3, imprimir_tabela=True, rotulo_var="I")
print(f"\n\033[1m \033[4mSolução (Gauss–Seidel):\033[0m I1={x_gs[0]:.8f}, I2={x_gs[1]:.8f}, I3={x_gs[2]:.8f}")
print(f"\033[1m \033[4mIterações (Gauss–Seidel):\033[0m {len(tab_gs)}\n")

# Teste (e) 4×4 com Gauss–Seidel
print("\n\033[1m \033[4m Teste (e) — Gauss–Seidel 4×4\033[0m")
x_gs4, tabela_gs4 = gauss_seidel(A4, b4, eps=1e-3, imprimir_tabela=True, rotulo_var="x")
print(f"\n\033[1m \033[4mSolução (GS 4×4):\033[0m {x_gs4}")
print(f"\033[1m \033[4mIterações (GS 4×4):\033[0m {len(tabela_gs4)}\n")


# Impressão das tabelas completas com nº de colunas detectado

if tab_j:
    n_c = len(tab_j[0]) - 2
    cols_c = ["Iter"] + [f"I{k+1}" for k in range(n_c)] + ["erro"]
    imprimir_tabela("Tabela de Jacobi", cols_c, tab_j)

if tab_gs:
    n_e = len(tab_gs[0]) - 2
    cols_e = ["Iter"] + [f"I{k+1}" for k in range(n_e)] + ["erro"]
    imprimir_tabela("Tabela de Gauss–Seidel", cols_e, tab_gs)

if tabela_j4:
    n_c4 = len(tabela_j4[0]) - 2
    cols_c4 = ["Iter"] + [f"x{k+1}" for k in range(n_c4)] + ["erro"]
    imprimir_tabela("Tabela de Jacobi 4×4 (teste)", cols_c4, tabela_j4)

if tabela_gs4:
    n_e4 = len(tabela_gs4[0]) - 2
    cols_e4 = ["Iter"] + [f"x{k+1}" for k in range(n_e4)] + ["erro"]
    imprimir_tabela("Tabela de Gauss–Seidel 4×4 (teste)", cols_e4, tabela_gs4)