# -*- coding: utf-8 -*-
"""EP3DaniloCho.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10R5HUq5t4LHqbvgjuhZku9tByrFSVTxN
"""

# EP3 - Parte 1: Regra de Simpson (simples e dupla precisão)
# Danilo Cho (NUSP 10769448)
# \033[1m e \033[0m Negrito
# \x1B[4m e \x1B[0m Sublinhado
# AMBOS \033[1m\x1B[4m  e \033[0m\x1B[0m



# EP3 - Parte 1: Simpson até p=25 sem estourar memória (soma em blocos)
import math
import numpy as np
import matplotlib.pyplot as plt

# Intervalo e valor exato
A, B = 0.0, 1.0
I_EXATO = 4.0  # ∫_0^1 (5 - 5x^4) dx = 4

# Agora vamos até p=25 para ambas as precisões
P_MIN = 1
P_MAX_SINGLE = 25
P_MAX_DOUBLE = 25

def f1(x):
    return 5.0 - 5.0 * x**4

def _sum_indices_blocked(a, h, N, start, step, dtype, block=1<<20):
    """
    Soma f1(a + h*k) para k=start, start+step, ..., < N, em blocos.
    Mantém toda a aritmética em 'dtype'.
    """
    dt = dtype
    s = dt(0)
    k = start
    while k < N:
        # vamos até no máx ~2*block índices crus para evitar vetores gigantes
        k_end = min(N, k + step * (block))
        idx = np.arange(k, k_end, step, dtype=np.int64)
        x = dt(a) + dt(h) * idx.astype(dt)
        s += np.sum(f1(x).astype(dt), dtype=dt)
        k = k_end
    return s

def simpson_composto(a, b, N, dtype=np.float64):
    """
    Simpson composto (N par), somando em blocos para permitir N=2^25.
    """
    if N % 2 != 0:
        raise ValueError("Simpson requer N par.")
    dt = dtype
    a = dt(a); b = dt(b); N = int(N)

    h = (b - a) / dt(N)

    # extremos
    acc = f1(a).astype(dt) + f1(b).astype(dt)

    # pontos ímpares (peso 4): k = 1,3,5,...,N-1
    s_odd  = _sum_indices_blocked(a, h, N, start=1, step=2, dtype=dt)
    # pontos pares (peso 2): k = 2,4,6,...,N-2
    s_even = _sum_indices_blocked(a, h, N, start=2, step=2, dtype=dt)

    acc += dt(4) * s_odd + dt(2) * s_even
    S = (h / dt(3.0)) * acc
    return float(S)

def roda_tabela(precision="single"):
    """Imprime tabela para p em 1..25 e devolve (p_list, err_list)."""
    if precision == "single":
        dt = np.float32
        P_MAX = P_MAX_SINGLE
    else:
        dt = np.float64
        P_MAX = P_MAX_DOUBLE

    print(f"\n\033[1m\033[4m# PARTE 1 — Simpson ({precision})\033[0m")
    print("\033[1m p |          N          |         Inum              |    erro=|Inum-4|\033[0m")
    print("---|---------------------|---------------------------|-------------------")

    p_list, err_list = [], []
    for p in range(P_MIN, P_MAX + 1):
        N = 1 << p
        Inum = simpson_composto(A, B, N, dtype=dt)
        err = abs(Inum - I_EXATO)
        print(f"\033[1m{p:2d}\033[0m | {N:21d} | {Inum: .16e} | {err: .6e}")
        if err > 0 and np.isfinite(err):
            p_list.append(p); err_list.append(err)
    return np.array(p_list, float), np.array(err_list, float)

def plota_log2_erros(p_s, e_s, p_d, e_d):
    plt.figure(figsize=(7.5, 5.0))
    if len(e_s): plt.plot(p_s, np.log2(e_s), "o-", label="simples (float32)")
    if len(e_d): plt.plot(p_d, np.log2(e_d), "o-", label="dupla (float64)")
    plt.xlabel("p  (N = 2^p)")
    plt.ylabel("log2(erro)")
    plt.title("Regra de Simpson — log2(erro) vs p (até p=25)")
    plt.grid(True, alpha=0.4)
    plt.legend()
    plt.show()

if __name__ == "__main__":
    p_s, e_s = roda_tabela("single")
    p_d, e_d = roda_tabela("double")

    # evita log2(0)
    mask_s = np.isfinite(e_s) & (e_s > 0)
    mask_d = np.isfinite(e_d) & (e_d > 0)

    plota_log2_erros(p_s[mask_s], e_s[mask_s], p_d[mask_d], e_d[mask_d])

# Parte 2: Pêndulo simples (trapézios)
# ------------------------------------------------------
# Calcular R = T / T_Galileu em função de θ₀
# utilizando a regra dos trapézios, evitando a singularidade.

M_TRAP = 4000  # número de subintervalos

def R_pendulo(theta0, M=M_TRAP):
    """
    R(theta0) = (2/pi) * ∫_0^{pi/2} 1/sqrt(1 - k^2 sin^2 xi) dxi
    Método dos trapézios em [0, pi/2 - gap] para evitar o ponto singular.
    """
    k2 = (1.0 - math.cos(theta0)) / 2.0
    a = 0.0
    b = math.pi / 2.0

    # corta um pequeno trecho antes do ponto singular (xi = pi/2)
    gap = 1e-5
    b_eff = b - gap

    h = (b_eff - a) / M

    def integrando(xi):
        s = math.sin(xi)
        den2 = 1.0 - k2 * s * s
        if den2 <= 0.0:
            den2 = 1e-300
        return 1.0 / math.sqrt(den2)

    acc = 0.5 * (integrando(a) + integrando(b_eff))
    for j in range(1, M):
        xi = a + j * h
        acc += integrando(xi)

    integral = acc * h
    return (2.0 / math.pi) * integral  # R = T/T_Galileu

def gera_tabela_e_grafico():
    # 20 valores uniformes em [0, π)
    thetas = np.linspace(0.0, math.pi * (1 - 1e-6), 20)
    Rvals = np.zeros_like(thetas)

    print("\n\033[1m\x1B[4m# PARTE 2 — Pêndulo (método dos trapézios)\033[0m\x1B[0m")
    print("\033[1m  i |   θ₀ (rad)       |   R = T/T_Galileu\033[0m")
    print("----|-------------------|-------------------")

    for i, th in enumerate(thetas, start=1):
        R = R_pendulo(float(th), M=M_TRAP)
        Rvals[i-1] = R
        print(f"\033[1m{i:3d}\033[0m | {th: .10f} | {R: .10f}")

    # Gráfico
    plt.figure(figsize=(7.5, 5.0))
    plt.plot(thetas, Rvals, "o-", lw=1.5)
    plt.xlabel(r"$\theta_0$ (rad)")
    plt.ylabel(r"$R(\theta_0) = T/T_{\mathrm{Galileu}}$")
    plt.title("Pêndulo — Razão do período R em função da amplitude inicial")
    plt.grid(True, alpha=0.4)
    plt.show()

    # Resposta da pergunta proposta
    print("\n\033[1m\x1B[4m O que acontece com o perídodo no limite quando θ₀ → π?:\033[0m\x1B[0m")

    print("• Quando θ₀ → π, a integral diverge, indicando que o período T tende a ∞.")

if __name__ == "__main__":
    gera_tabela_e_grafico()


# Parte 3: Monte Carlo (parábola) + LCG

SEED = 10769448
A = 1664525
C = 1013904223
M = 2147483647
AREA_EXATA = 2.0/3.0  # não é usado na tabela nesta versão

def lcg(seed):
    z = int(seed) % M
    while True:
        z = (A*z + C) % M
        yield z / M

def primeiros_dez_aleatorios(seed):
    g = lcg(seed)
    return [next(g) for _ in range(10)]

def tentativa_MonteCarlo(seed, npts=100):
    g = lcg(seed)
    dentro = 0
    for _ in range(npts):
        x = next(g); y = next(g)
        if y <= (1.0 - x*x):
            dentro += 1
    return dentro / npts

def estudo_monte_carlo(seed, Nt_max=131072, npts=100, plot=True):
    Nt_vals, Im_vals, sigm_vals = [], [], []

    print("\n\033[1m\x1B[4m# PARTE 3.c) Monte Carlo \033[0m\x1B[0m")
    print("\033[1mNt       Im (média)        sigma           sigma_m\033[0m")
    print("-"*56)

    Nt = 2
    while Nt <= Nt_max:
        Ii = np.array([tentativa_MonteCarlo(seed + 37*i, npts=npts) for i in range(Nt)], float)
        Im    = float(Ii.mean())
        sigma = float(Ii.std(ddof=1)) if Nt > 1 else 0.0
        sigma_m = sigma / math.sqrt(Nt) if Nt > 0 else float('nan')

        print(f"\033[1m{Nt:<8d}\033[0m {Im: .6f}       {sigma: .6f}      {sigma_m: .6f}")

        Nt_vals.append(Nt); Im_vals.append(Im); sigm_vals.append(sigma_m)
        Nt *= 2

    Nt_vals  = np.array(Nt_vals, int)
    Im_vals  = np.array(Im_vals, float)
    sigm_vals = np.array(sigm_vals, float)

    if plot:
        plt.figure(figsize=(7.5,4.6))
        plt.plot(Nt_vals, Im_vals, "o-")
        plt.xscale("log", base=2)
        plt.xlabel("Nt (log₂)"); plt.ylabel("Im (média)")
        plt.title(f"Monte Carlo: Im vs Nt (cada tentativa usa {npts} pontos)")
        plt.grid(True, alpha=0.4)
        plt.show()

        plt.figure(figsize=(7.5,4.6))
        plt.plot(Nt_vals, sigm_vals, "o-")
        plt.xscale("log", base=2); plt.yscale("log")
        plt.xlabel("Nt (log₂)"); plt.ylabel("sigma_m (log)")
        plt.title("Monte Carlo: erro da média σ_m vs Nt")
        plt.grid(True, which="both", alpha=0.4)
        plt.show()

if __name__ == "__main__":
    # (a) 10 primeiros
    print("\n\033[1m\x1B[4m# PARTE 3.a) LCG (10 primeiros)\033[0m\x1B[0m")
    for i, u in enumerate(primeiros_dez_aleatorios(SEED), 1):
        print(f"\033[1m{i:2d}\033[0m: {u:.12f}")

    # (b) Uma tentativa com 100 pontos
    I_uma = tentativa_MonteCarlo(SEED, npts=100)
    print(f"\033[1m\x1B[4m\n# PARTE 3.b)\033[0m\x1B[0m Uma tentativa (100 pontos): \033[1m\x1B[4mI ≈ {I_uma:.6f}\033[0m\x1B[0m")

    # (c) Estudo estatístico
    estudo_monte_carlo(SEED, Nt_max=131072, npts=100, plot=True)