# -*- coding: utf-8 -*-
"""Projeto_final_DaniloCho.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16dWlkBwhXTScK3SxFFvX-dmRJPSpSrF8
"""

"""
Projeto Final - PMT3533 - Termohidráulica de Sistemas de Geração de Potência II

Modelo unidimensional do canal mais quente de um elemento combustível tipo placa.
O programa calcula, via Método Nodal, as temperaturas do fluido, da interface
fluido–revestimento, do revestimento e do combustível ao longo do canal,
para três cenários:

1) Operação normal
2) LOFA em t = 32 s
3) LOFA em t = 100 s

O código também determina o coeficiente de transferência de calor convectivo (h)
ao longo do canal e salva os resultados em um arquivo Excel.
"""

!pip install iapws

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from iapws import IAPWS97


# 1. Parâmetros geométricos e dados gerais do problema

# Dimensões (m)
t_clad = 0.00038      # espessura do revestimento
t_fuel = 0.00076      # espessura do combustível
gap_channel = 0.00289 # altura do canal de refrigeração
width_channel = 0.0671  # largura do canal de refrigeração
width_plate = 0.0626    # largura da placa combustível
length_plate = 0.60     # comprimento da placa

# Núcleo
n_elements = 25      # número de elementos combustíveis no núcleo
n_plates = 18        # número de placas por elemento
n_channels = 17      # número de canais internos por EC (15 + 2 canais externos -> mas usa 17 internos, como no exemplo)
P_total_nominal = 5.0e6  # potência nominal do reator [W]

# Vazão (informada por elemento combustível)
V_dot_EC_m3_per_h = 22.8   # [m³/h] por EC em operação normal

# Propriedades do material (revestimento de alumínio)
k_clad = 180.0  # [W/m.K]

# Condições de entrada
T_inlet_C = 30.0            # [°C]
T_inlet_K = T_inlet_C + 273.15
P_inlet_kPa = 160.0         # [kPa]
P_outlet_kPa = 150.0        # [kPa]

# Fator radial de potência (canal mais quente)
f_radial = 1.914

# Frações de potência e vazão para cada condição
# (valores retirados da Tabela e do enunciado)
CONDICOES = {
    1: {"nome": "Operação normal",       "FP": 1.0,     "FV": 1.0},
    2: {"nome": "LOFA t = 32 s",         "FP": 0.0500,  "FV": 0.5273},
    3: {"nome": "LOFA t = 100 s",        "FP": 0.0389,  "FV": 0.1353},
}

# 2. Funções auxiliares

def k_fuel_from_temperature(T_K: float) -> float:
    """
    Condutividade térmica do combustível U3Si2 em função da temperatura.
    A correlação original é dada em unidades imperiais; aqui é feita
    a conversão para SI (W/m.K).

    Entrada:
        T_K : temperatura em Kelvin

    Saída:
        k_fuel_SI : condutividade térmica em W/m.K
    """
    # Kelvin -> Celsius -> Fahrenheit
    T_C = T_K - 273.15
    T_F = T_C * 9.0/5.0 + 32.0

    # Correlação empírica em BTU/(h.ft.°F)
    k_fuel_imperial = (3978.1 / (692.61 + T_F)) + 6.023366e-12 * (T_F + 460.0)**3

    # Conversão para W/m.K
    factor_BTU_to_W = 1.730735
    k_fuel_SI = k_fuel_imperial * factor_BTU_to_W
    return k_fuel_SI


def water_properties(T_K: float, P_MPa: float) -> IAPWS97:
    """
    Retorna um objeto IAPWS97 com as propriedades da água
    em função da temperatura (K) e pressão (MPa).
    """
    return IAPWS97(T=T_K, P=P_MPa)


def build_axial_mesh(n_nodes: int, L: float) -> np.ndarray:
    """
    Constrói a malha axial (posição dos centros dos nós) ao longo da placa,
    usando coordenada x variando de -L/2 até L/2.
    """
    dx = L / n_nodes
    x_start = -L / 2.0 + dx / 2.0
    x_end = L / 2.0 - dx / 2.0
    x_nodes = np.linspace(x_start, x_end, n_nodes)
    return x_nodes


def heat_flux_profile(x_nodes: np.ndarray, q_mean: float, L: float) -> np.ndarray:
    """
    Calcula o fluxo de calor local em cada nó usando o perfil:
        q''(x) = f_radial * q_mean * cos( (pi/2) * x / (L/2) )
    """
    return f_radial * q_mean * np.cos((np.pi / 2.0) * (x_nodes / (L / 2.0)))


def compute_geometry():
    """
    Calcula área de escoamento, perímetro molhado e diâmetro hidráulico do canal.
    """
    A_flow = width_channel * gap_channel
    P_wet = 2.0 * (width_channel + gap_channel)
    D_h = 4.0 * A_flow / P_wet
    return A_flow, P_wet, D_h


def choose_condition() -> int:
    """
    Exibe o menu de condições de operação e retorna a opção escolhida.
    """
    print("\nSelecione a condição de operação:")
    print("  1 - Operação normal")
    print("  2 - LOFA em t = 32 s")
    print("  3 - LOFA em t = 100 s")
    opt = int(input("Digite o número da condição desejada: "))
    if opt not in CONDICOES:
        print("Opção inválida. Usando condição 1 (Operação normal) por padrão.")
        opt = 1
    return opt


# 3. Função principal de cálculo pelo Método Nodal

def solve_channel(n_nodes: int, cond_id: int):
    """
    Resolve o problema termohidráulico para o canal mais quente, dado:
      - número de nós da malha (n_nodes)
      - condição de operação (cond_id: 1, 2 ou 3)

    Retorna um dicionário com:
      x_nodes, T_fluid, T_interface, T_clad, T_fuel, h_local, P_profile
    """
    # Geometria básica do canal
    A_flow, P_wet, D_h = compute_geometry()

    # Dados da condição
    FP = CONDICOES[cond_id]["FP"]
    FV = CONDICOES[cond_id]["FV"]

    # Potência ajustada
    P_total = P_total_nominal * FP
    # Vazão volumétrica por EC (m³/s)
    V_dot_EC = V_dot_EC_m3_per_h * FV / 3600.0
    # Vazão por canal interno
    V_dot_channel = V_dot_EC / n_channels

    # Pressão ao longo do canal (kPa -> MPa)
    P_profile_kPa = np.linspace(P_inlet_kPa, P_outlet_kPa, n_nodes)
    P_profile_MPa = P_profile_kPa / 1000.0

    # Potência por placa
    P_plate = P_total / (n_elements * n_plates)

    # Área total de troca por placa (duas faces)
    A_heat = 2.0 * length_plate * width_plate

    # Fluxo médio
    q_mean = P_plate / A_heat

    # Malha axial
    x_nodes = build_axial_mesh(n_nodes, length_plate)

    # Fluxo de calor em cada nó (com fator radial)
    q_local = heat_flux_profile(x_nodes, q_mean, length_plate)

    # Propriedades de entrada da água
    water_in = water_properties(T_inlet_K, P_inlet_kPa / 1000.0)
    rho_in = water_in.rho

    # Vazão mássica no canal
    m_dot = rho_in * V_dot_channel

    # Velocidade média (assumida praticamente constante)
    v_mean = V_dot_channel / A_flow

    # Vetores de saída
    T_fluid = np.zeros(n_nodes)       # [K]
    T_interface = np.zeros(n_nodes)   # [K]
    T_clad_vec = np.zeros(n_nodes)    # [K]
    T_fuel_vec = np.zeros(n_nodes)    # [K]
    h_local = np.zeros(n_nodes)       # [W/m².K]

    # Passo axial para balanço de energia
    dx = length_plate / n_nodes
    # Área de troca correspondente a cada nó
    A_node = A_heat / n_nodes

    # Nó 0: balanço usando condições de entrada
    props0 = water_properties(T_inlet_K, P_profile_MPa[0])
    cp0 = props0.cp * 1000.0     # J/kg.K
    mu0 = props0.mu
    k0 = props0.k

    Re0 = rho_in * v_mean * D_h / mu0
    Pr0 = cp0 * mu0 / k0
    Nu0 = 0.023 * (Re0**0.8) * (Pr0**0.4)
    h0 = Nu0 * k0 / D_h

    h_local[0] = h0
    T_fluid[0] = T_inlet_K + (q_local[0] * A_node) / (m_dot * cp0)

    # Temperaturas em camadas sólidas no nó 0
    T_interface[0] = T_fluid[0] + q_local[0] / h0
    T_clad_vec[0] = T_interface[0] + q_local[0] * t_clad / k_clad

    kf0 = k_fuel_from_temperature(T_clad_vec[0])
    T_fuel_vec[0] = T_clad_vec[0] + q_local[0] * t_fuel / (4.0 * kf0)

    # Demais nós
    for i in range(1, n_nodes):
        # Usa cp do nó anterior para o balanço de energia
        props_prev = water_properties(T_fluid[i-1], P_profile_MPa[i-1])
        cp_prev = props_prev.cp * 1000.0

        # Balanço de energia do fluido
        T_fluid[i] = T_fluid[i-1] + (q_local[i] * A_node) / (m_dot * cp_prev)

        # Propriedades locais no nó i
        props_i = water_properties(T_fluid[i], P_profile_MPa[i])
        rho_i = props_i.rho
        mu_i = props_i.mu
        k_i = props_i.k
        cp_i = props_i.cp * 1000.0

        # Atualiza números adimensionais e coeficiente h
        Re_i = rho_i * v_mean * D_h / mu_i
        Pr_i = cp_i * mu_i / k_i
        Nu_i = 0.023 * (Re_i**0.8) * (Pr_i**0.4)
        h_i = Nu_i * k_i / D_h
        h_local[i] = h_i

        # Interface
        T_interface[i] = T_fluid[i] + q_local[i] / h_i
        # Revestimento
        T_clad_vec[i] = T_interface[i] + q_local[i] * t_clad / k_clad
        # Combustível (condutividade dependente da temperatura)
        k_fuel_i = k_fuel_from_temperature(T_clad_vec[i])
        T_fuel_vec[i] = T_clad_vec[i] + q_local[i] * t_fuel / (4.0 * k_fuel_i)

    # Retorna tudo em um dicionário
    return {
        "x": x_nodes,
        "T_fluid": T_fluid,
        "T_interface": T_interface,
        "T_clad": T_clad_vec,
        "T_fuel": T_fuel_vec,
        "h": h_local,
        "P_kPa": P_profile_kPa,
    }


# 4. Rotinas de pós-processamento (gráficos e planilha)

def plot_temperature_profiles(x, T_fluid, T_interface, T_clad, T_fuel, cond_id: int):
    """
    Gera o gráfico das temperaturas ao longo do canal.
    """
    plt.figure(figsize=(10, 6))
    plt.plot(x, T_fluid - 273.15, label="Fluido", marker="x")
    plt.plot(x, T_interface - 273.15, label="Interface", marker="^")
    plt.plot(x, T_clad - 273.15, label="Revestimento", marker="s")
    plt.plot(x, T_fuel - 273.15, label="Combustível", marker="o")
    plt.xlabel("Posição axial x [m]")
    plt.ylabel("Temperatura [°C]")
    plt.title(f"Distribuição de temperaturas ao longo do canal ({CONDICOES[cond_id]['nome']})")
    plt.grid(True)
    plt.legend()
    plt.tight_layout()
    plt.show()


def plot_h_profile(x, h_local, cond_id: int):
    """
    Gera o gráfico do coeficiente de convecção ao longo do canal.
    """
    plt.figure(figsize=(10, 6))
    plt.plot(x, h_local, label="h(x)", marker="o")
    plt.xlabel("Posição axial x [m]")
    plt.ylabel("h [W/m².K]")
    plt.title(f"Coeficiente de transferência de calor convectivo ({CONDICOES[cond_id]['nome']})")
    plt.grid(True)
    plt.legend()
    plt.tight_layout()
    plt.show()


def export_to_excel(x, T_fluid, T_interface, T_clad, T_fuel, h_local, P_kPa, cond_id: int, n_nodes: int):
    """
    Cria um DataFrame com os resultados nodais e salva em um arquivo .xlsx.
    """
    data = {
        "x [m]": x,
        "T_fluido [°C]": T_fluid - 273.15,
        "T_interface [°C]": T_interface - 273.15,
        "T_revestimento [°C]": T_clad - 273.15,
        "T_combustivel [°C]": T_fuel - 273.15,
        "h [W/m².K]": h_local,
        "Pressão [kPa]": P_kPa,
    }
    df = pd.DataFrame(data)
    filename = f"resultados_condicao_{cond_id}_{n_nodes}_nos.xlsx"
    df.to_excel(filename, index=False)
    print(f"\nArquivo '{filename}' salvo com sucesso.")


# 5. Ponto de entrada principal

def main():
    print("=== PROJETO FINAL - PMT3533 ===")
    n_nodes = int(input("Informe o número de nós da malha axial: "))
    cond_id = choose_condition()

    resultados = solve_channel(n_nodes, cond_id)

    # Gráficos
    plot_temperature_profiles(
        resultados["x"],
        resultados["T_fluid"],
        resultados["T_interface"],
        resultados["T_clad"],
        resultados["T_fuel"],
        cond_id,
    )

    plot_h_profile(
        resultados["x"],
        resultados["h"],
        cond_id,
    )

    # Exportar planilha
    export_to_excel(
        resultados["x"],
        resultados["T_fluid"],
        resultados["T_interface"],
        resultados["T_clad"],
        resultados["T_fuel"],
        resultados["h"],
        resultados["P_kPa"],
        cond_id,
        n_nodes,
    )


if __name__ == "__main__":
    main()